
package serivicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapDataService", targetNamespace = "http://serivicios/", wsdlLocation = "http://localhost:7777/ws/SoapData?wsdl")
public class SoapDataService
    extends Service
{

    private final static URL SOAPDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPDATASERVICE_EXCEPTION;
    private final static QName SOAPDATASERVICE_QNAME = new QName("http://serivicios/", "SoapDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7777/ws/SoapData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPDATASERVICE_WSDL_LOCATION = url;
        SOAPDATASERVICE_EXCEPTION = e;
    }

    public SoapDataService() {
        super(__getWsdlLocation(), SOAPDATASERVICE_QNAME);
    }

    public SoapDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPDATASERVICE_QNAME, features);
    }

    public SoapDataService(URL wsdlLocation) {
        super(wsdlLocation, SOAPDATASERVICE_QNAME);
    }

    public SoapDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPDATASERVICE_QNAME, features);
    }

    public SoapDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapData
     */
    @WebEndpoint(name = "SoapDataPort")
    public SoapData getSoapDataPort() {
        return super.getPort(new QName("http://serivicios/", "SoapDataPort"), SoapData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapData
     */
    @WebEndpoint(name = "SoapDataPort")
    public SoapData getSoapDataPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serivicios/", "SoapDataPort"), SoapData.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPDATASERVICE_EXCEPTION!= null) {
            throw SOAPDATASERVICE_EXCEPTION;
        }
        return SOAPDATASERVICE_WSDL_LOCATION;
    }

}
