
package serivicios;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapData", targetNamespace = "http://serivicios/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapData {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<serivicios.Post>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPostsUsuario", targetNamespace = "http://serivicios/", className = "serivicios.GetPostsUsuario")
    @ResponseWrapper(localName = "getPostsUsuarioResponse", targetNamespace = "http://serivicios/", className = "serivicios.GetPostsUsuarioResponse")
    @Action(input = "http://serivicios/SoapData/getPostsUsuarioRequest", output = "http://serivicios/SoapData/getPostsUsuarioResponse")
    public List<Post> getPostsUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearPost", targetNamespace = "http://serivicios/", className = "serivicios.CrearPost")
    @ResponseWrapper(localName = "crearPostResponse", targetNamespace = "http://serivicios/", className = "serivicios.CrearPostResponse")
    @Action(input = "http://serivicios/SoapData/crearPostRequest", output = "http://serivicios/SoapData/crearPostResponse")
    public String crearPost(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
